Support "lang" parameter for Konkorde filters
kuzzleio/sdk-javascript pull request #575
Opened 2020-12-16 10:12 UTC by Yoann-Abbes

## What does this PR do?

Since Kuzzle 2.8.0 supports the "lang" parameter to handle Konkorde filters, we need to add it in SDKs for the API methods who accept it. 

### How should this be manually tested?

  - Step 1 :
  - Step 2 :
  - Step 3 :  
  ...

### Other changes

### Boyscout

2020-12-16 16:14 UTC, Aschen requested changes
Can you add an example in the existing snippet for `document:search` at least ?
To ensure it's working with search result `next` method but also to show the feature to users

2020-12-16 16:14 UTC, Aschen commented on doc/7/controllers/auth/search-api-keys/index.md
> +<SinceBadge version="change-me"/>
```suggestion
<SinceBadge version="auto-version"/>
```

2020-12-16 16:14 UTC, Aschen commented on doc/7/controllers/auth/search-api-keys/index.md
> +<SinceBadge version="change-me"/>
Other badges must be updated as well

2020-12-22 08:37 UTC, Njuelle approved these changes

2020-12-23 15:03 UTC, rolljee approved these changes

2020-12-28 16:17 UTC, rolljee requested changes

2020-12-28 16:17 UTC, rolljee commented on doc/7/controllers/document/delete-by-query/snippets/delete-by-query-koncorde.js
> +}
missing newline

2020-12-28 16:17 UTC, rolljee commented on doc/7/controllers/document/update-by-query/snippets/update-by-query-es.test.yml
> +  - "{ _id: 'document_2', _version: 2, status: 200 }"
missing newline

2020-12-29 08:23 UTC, rolljee approved these changes

2020-12-29 14:27 UTC, Aschen requested changes

2020-12-29 14:27 UTC, Aschen commented on doc/7/controllers/auth/search-api-keys/index.md
> +With the [ElasticSearch Query DSL](https://www.elastic.co/guide/en/elasticsearch/reference/7.3/query-dsl.html) syntax.
```suggestion
With the [ElasticSearch Query DSL](https://www.elastic.co/guide/en/elasticsearch/reference/7.4/query-dsl.html) syntax.
```

2020-12-29 14:27 UTC, Aschen commented on doc/7/controllers/auth/search-api-keys/snippets/search-api-keys-koncorde.js
> +          "expiresAt": 31557600000,
Missing from original doc
```suggestion
          "expiresAt": 31557600000,
          "fingerprint": "4ee98cb8c614e99213e7695f822e42325d86c93cfaf39cb40e860939e784c8e6",
```

2020-12-29 14:27 UTC, Aschen commented on doc/7/controllers/auth/search-api-keys/snippets/search-api-keys-koncorde.js
> +          "expiresAt": 31557600000,
Missing from original doc
```suggestion
          "expiresAt": 31557600000,
          "fingerprint": "f822e42325d86c93cfaf39cb40e860939e784c8e64ee98cb8c614e99213e7695",
```

2020-12-29 14:27 UTC, Aschen commented on doc/7/controllers/document/delete-by-query/index.md
> +With the [ElasticSearch Query DSL](https://www.elastic.co/guide/en/elasticsearch/reference/7.3/query-dsl.html) syntax.
```suggestion
With the [ElasticSearch Query DSL](https://www.elastic.co/guide/en/elasticsearch/reference/7.4/query-dsl.html) syntax.
```

2020-12-29 14:27 UTC, Aschen commented on doc/7/controllers/document/search/index.md
> +With the [ElasticSearch Query DSL](https://www.elastic.co/guide/en/elasticsearch/reference/7.3/query-dsl.html) syntax.
```suggestion
With the [ElasticSearch Query DSL](https://www.elastic.co/guide/en/elasticsearch/reference/7.4/query-dsl.html) syntax.
```

2020-12-29 14:27 UTC, Aschen commented on doc/7/controllers/document/update-by-query/index.md
> +With the [ElasticSearch Query DSL](https://www.elastic.co/guide/en/elasticsearch/reference/7.3/query-dsl.html) syntax.
```suggestion
With the [ElasticSearch Query DSL](https://www.elastic.co/guide/en/elasticsearch/reference/7.4/query-dsl.html) syntax.
```

2020-12-29 14:27 UTC, Aschen commented on doc/7/controllers/security/search-api-keys/index.md
> +With the [ElasticSearch Query DSL](https://www.elastic.co/guide/en/elasticsearch/reference/7.3/query-dsl.html) syntax.
```suggestion
With the [ElasticSearch Query DSL](https://www.elastic.co/guide/en/elasticsearch/reference/7.4/query-dsl.html) syntax.
```

2020-12-29 14:27 UTC, Aschen commented on doc/7/controllers/security/search-users/index.md
> +The search query to apply to users content, using [ElasticSearch Query DSL](https://www.elastic.co/guide/en/elasticsearch/reference/7.3/query-dsl.html) or the [Koncorde Filters DSL](/core/2/api/konco
```suggestion
The search query to apply to users content, using [ElasticSearch Query DSL](https://www.elastic.co/guide/en/elasticsearch/reference/7.4/query-dsl.html) or the [Koncorde Filters DSL](/core/2/api/koncorde-filters-syntax) syntax.
```

2020-12-29 14:27 UTC, Aschen commented on doc/7/controllers/security/search-users/index.md
> +With the [ElasticSearch Query DSL](https://www.elastic.co/guide/en/elasticsearch/reference/7.3/query-dsl.html) syntax.
```suggestion
With the [ElasticSearch Query DSL](https://www.elastic.co/guide/en/elasticsearch/reference/7.4/query-dsl.html) syntax.
```

2020-12-29 14:27 UTC, Aschen commented on src/controllers/Auth.ts
> +    options: { from?: number, size?: number, lang?: string } = {}
Missing parameter documentation in the method description

2020-12-29 14:27 UTC, Aschen commented on src/controllers/Document.ts
> +    options: { refresh?: 'wait_for', source?: boolean, lang?: string} = {}
Nit
```suggestion
    options: { refresh?: 'wait_for', source?: boolean, lang?: string } = {}
```

2020-12-29 14:27 UTC, Aschen commented on src/controllers/Document.ts
> +    options: { queuable?: boolean, refresh?: string, lang?: string} = {}
Nitpicking
```suggestion
    options: { queuable?: boolean, refresh?: string, lang?: string } = {}
```

2020-12-30 10:08 UTC, Aschen approved these changes

2021-01-04 09:08 UTC, Njuelle approved these changes

2021-01-04 09:09 UTC, merged