Add [auth|security]:checkRights
kuzzleio/sdk-javascript pull request #577
Opened 2020-12-16 12:35 UTC by Yoann-Abbes

## What does this PR do?

Add [auth|security]:checkRights https://github.com/kuzzleio/sdk-javascript/issues/571

### How should this be manually tested?

  - Step 1 :
  - Step 2 :
  - Step 3 :  
  ...

### Other changes

### Boyscout

2020-12-17 14:09 UTC, Aschen requested changes
I'm sorry Kuzzle documentation was not accurate, can you correct this PR with the new doc ? 
https://github.com/kuzzleio/kuzzle/pull/1912

Also can you choose better names for method arguments since they will be displayed in the editor with the jsdoc

2020-12-17 14:09 UTC, Aschen commented on doc/7/controllers/auth/check-rights/index.md
> +| `_id` | <pre>string</pre> | User [kuid](/core/2/guides/main-concepts/authentication#kuzzle-user-identifier-kuid) |
```suggestion
| `kuid` | <pre>string</pre> | User [kuid](/core/2/guides/main-concepts/authentication#kuzzle-user-identifier-kuid) |
```

2020-12-17 14:09 UTC, Aschen commented on doc/7/controllers/auth/check-rights/index.md
> +| `body` | <pre>object</pre> | Contains a `request` |
```suggestion
| `requestPayload` | <pre>object</pre> | Contains a [RequestPayload](/core/2/api/payloads/request) |
```

2020-12-22 08:35 UTC, Njuelle approved these changes

2020-12-23 15:38 UTC, rolljee approved these changes

2020-12-29 13:49 UTC, Aschen requested changes
The methods should directly returns the boolean IMHO

2020-12-29 13:49 UTC, Aschen commented on doc/7/controllers/auth/check-rights/snippets/check-rights.js
> +    'name': 'Melis'
```suggestion
    name: 'Melis'
```

2020-12-29 13:49 UTC, Aschen commented on doc/7/controllers/auth/check-rights/index.md
> +title: checkRights
```suggestion
title: checkRights
description: Checks if an API action can be executed by the current user
```

2020-12-29 13:49 UTC, Aschen commented on doc/7/controllers/security/check-rights/index.md
> +
```suggestion
<SinceBadge version="auto-version"/>
```

2020-12-29 13:49 UTC, Aschen commented on doc/7/controllers/security/check-rights/snippets/check-rights.test.yml
> +description: Checks if an API action can be executed by the current user
```suggestion
description: Checks if an API action can be executed by a user
```

2020-12-29 13:49 UTC, Aschen commented on doc/7/controllers/security/check-rights/snippets/check-rights.js
> +    'name': 'Melis'
```suggestion
    name: 'Melis'
```

2020-12-29 13:49 UTC, Aschen commented on doc/7/controllers/security/check-rights/index.md
> +title: checkRights
```suggestion
title: checkRights
description: Checks if an API action can be executed by a user
```

2020-12-29 13:49 UTC, Aschen commented on doc/7/controllers/auth/check-rights/index.md
> +Checks if the provided API request can be executed by a user.
```suggestion
Checks if the provided API request can be executed by the current logged user.
```

2020-12-29 13:49 UTC, Aschen commented on doc/7/controllers/auth/check-rights/index.md
> +checkRights(kuid, requestPayload)
```suggestion
checkRights(requestPayload)
```

2020-12-29 13:49 UTC, Aschen commented on doc/7/controllers/auth/check-rights/index.md
> +| `kuid` | <pre>string</pre> | User [kuid](/core/2/guides/main-concepts/authentication#kuzzle-user-identifier-kuid) |
```suggestion
|--- |--- |--- |
```

2020-12-29 13:49 UTC, Aschen commented on doc/7/controllers/auth/check-rights/index.md
> +## Body properties
```suggestion
## `requestPayload`
```

2020-12-29 13:49 UTC, Aschen commented on doc/7/controllers/security/check-rights/index.md
> +## Body properties
```suggestion
## `requestPayload`
```

2020-12-29 13:49 UTC, Aschen commented on doc/7/controllers/security/check-rights/index.md
> +The body must contain a [RequestPayload](/core/2/api/payloads/request) with at least the following properties:
```suggestion
The [RequestPayload](/core/2/api/payloads/request) must contains at least the following properties:
```

2020-12-29 13:49 UTC, Aschen commented on src/controllers/Auth.ts
> +      .then(response => response.result);
```suggestion
      .then(response => response.result.allowed);
```

2020-12-29 13:49 UTC, Aschen commented on src/controllers/Security.js
> +      .then(response => response.result);
```suggestion
      .then(response => response.result.allowed);
```

2020-12-29 13:49 UTC, Aschen commented on src/controllers/Security.js
> +  checkRights(userId, body) {
```suggestion
  checkRights(kuid requestPayload) {
```

2020-12-29 13:49 UTC, Aschen commented on src/controllers/Security.js
> +      userId,
```suggestion
      userId: kuid,
```

2020-12-29 13:49 UTC, Aschen commented on src/controllers/Security.js
> +      body,
```suggestion
      body: requestPayload,
```

2020-12-29 13:49 UTC, Aschen commented on doc/7/controllers/security/check-rights/snippets/check-rights.js
> +  const result = await kuzzle.security.checkRights('foo', requestPayload);
```suggestion
  const allowed = await kuzzle.security.checkRights('foo', requestPayload);
```

2020-12-29 13:49 UTC, Aschen commented on doc/7/controllers/security/check-rights/snippets/check-rights.js
> +  console.log(result.allowed);
```suggestion
  console.log(allowed);
```

2020-12-29 13:49 UTC, Aschen commented on doc/7/controllers/security/check-rights/index.md
> +The returned result contains the following property:
The `allowed` boolean is directly returned

2020-12-29 16:09 UTC, rolljee approved these changes

2021-01-07 13:12 UTC, Njuelle approved these changes

2021-01-11 14:28 UTC, Aschen commented on src/controllers/Auth.ts
> +      .then(response => response.result);
```suggestion
      .then(response => response.result.allowed);
```

2021-01-11 14:28 UTC, Aschen approved these changes

2021-01-11 15:05 UTC, merged