[HOTFIX] relative import in Auth.ts
kuzzleio/sdk-javascript pull request #590
Opened 2021-01-21 15:40 UTC by xbill82

Fixes this [build error](https://app.netlify.com/sites/kuzzle-admin-console/deploys/60099111179c6800077bab7a) (seen on the Amin Console Netlify build). Webpack looks for a package called `src/types/RequestPayload` since the path doesn't start with `.`.

2021-01-21 16:35 UTC, Aschen approved these changes
Autolinter

2021-01-21 16:35 UTC, Aschen commented on src/controllers/Auth.ts
> +  validateMyCredentials(
```suggestion
  validateMyCredentials (
```

2021-01-21 16:35 UTC, Aschen commented on src/controllers/Auth.ts
> +  updateSelf(
```suggestion
  updateSelf (
```

2021-01-21 16:35 UTC, Aschen commented on src/controllers/Auth.ts
> +  updateMyCredentials(
```suggestion
  updateMyCredentials (
```

2021-01-21 16:35 UTC, Aschen commented on src/controllers/Auth.ts
> +  logout(): Promise<void> {
```suggestion
  logout (): Promise<void> {
```

2021-01-21 16:35 UTC, Aschen commented on src/controllers/Auth.ts
> +  login(
```suggestion
  login (
```

2021-01-21 16:35 UTC, Aschen commented on src/controllers/Auth.ts
> +  getStrategies(options: { queuable?: boolean } = {}): Promise<Array<string>> {
```suggestion
  getStrategies (options: { queuable?: boolean } = {}): Promise<Array<string>> {
```

2021-01-21 16:35 UTC, Aschen commented on src/controllers/Auth.ts
> +  getMyRights(
```suggestion
  getMyRights (
```

2021-01-21 16:35 UTC, Aschen commented on src/controllers/Auth.ts
> +  getCurrentUser(options: { queuable?: boolean } = {}): Promise<User> {
```suggestion
  getCurrentUser (options: { queuable?: boolean } = {}): Promise<User> {
```

2021-01-21 16:35 UTC, Aschen commented on src/controllers/Auth.ts
> +  deleteMyCredentials(
```suggestion
  deleteMyCredentials (
```

2021-01-21 16:35 UTC, Aschen commented on src/controllers/Auth.ts
> +  credentialsExist(
```suggestion
  credentialsExist (
```

2021-01-21 16:35 UTC, Aschen commented on src/controllers/Auth.ts
> +  createMyCredentials(
```suggestion
  createMyCredentials (
```

2021-01-21 16:35 UTC, Aschen commented on src/controllers/Auth.ts
> +  checkToken(token?: string): Promise<{
```suggestion
  checkToken (token?: string): Promise<{
```

2021-01-21 16:35 UTC, Aschen commented on src/controllers/Auth.ts
> +  checkRights(requestPayload: RequestPayload): Promise<boolean> {
```suggestion
  checkRights (requestPayload: RequestPayload): Promise<boolean> {
```

2021-01-21 16:35 UTC, Aschen commented on src/controllers/Auth.ts
> +    if (!this.authenticationToken
```suggestion
  authenticateRequest (request: any) {
    if ( ! this.authenticationToken
```

2021-01-21 16:35 UTC, Aschen commented on src/controllers/Auth.ts
> +  constructor(kuzzle) {
```suggestion
  constructor (kuzzle) {
```

2021-01-21 16:36 UTC, Aschen requested changes
You need to bump the package version `npm version patch`

2021-01-22 09:31 UTC, Aschen approved these changes

2021-01-22 12:18 UTC, scottinet approved these changes

2021-01-22 12:18 UTC, merged