Implement the new Index:Stats
kuzzleio/sdk-javascript pull request #613
Opened 2021-03-09 19:16 UTC by Leodau

## What does this PR do?
This **PR** implements the recently added [index:stats](https://docs.kuzzle.io/core/2/api/controllers/index/stats/) _(@ Kuzzle Backend v2.10.0)_
So it can be used directly, instead of having to use **query** to access it.

#### Todo:

- [x] Implementation
- [ ] Unit Testing
- [ ] Doc + Code Snippet

### How should this be manually tested?

1. Launch a Kuzzle stack.
2. Directly use `sdk.security.getUserStrategies(userKuid)`
3. Verify that you get stats that make sense.

Closes #608

2021-03-11 08:46 UTC, scottinet approved these changes

2021-03-11 09:33 UTC, Aschen requested changes

2021-03-11 09:33 UTC, Aschen commented on doc/7/controllers/index/stats/snippets/stats.js
> +console.log(JSON.stringify(stats));
Can you add the JSON structure in comment please?

So user know how to manipulate the result then

2021-03-11 15:27 UTC, Aschen approved these changes

2021-03-11 15:27 UTC, Aschen commented on src/controllers/Index.ts
> +  stats (options: { queuable?: boolean } = {}): Promise<any> {
```suggestion
  stats (options: { queuable?: boolean } = {}): Promise<JSONObject> {
```

2021-03-11 15:36 UTC, Leodau commented on src/controllers/Index.ts
> +  stats (options: { queuable?: boolean } = {}): Promise<any> {
Oh good catch

2021-03-12 09:59 UTC, alexandrebouthinon reviewed
To fix unit tests, you need to add this line at the top of `src/controllers/Index.ts`:
```js
import { JSONObject } from '../types';
```

2021-03-19 14:20 UTC, alexandrebouthinon approved these changes

2021-03-19 14:21 UTC, merged