Remove mentions of admin console tests in workflow
kuzzleio/sdk-javascript pull request #626
Opened 2021-04-08 14:31 UTC by MathieuVeber

## What does this PR do ?

Remove mentions of admin console tests in workflow. Indeed these tests were commented in another [PR](https://github.com/kuzzleio/sdk-javascript/pull/625) and CI fail because of that.

2021-04-08 14:56 UTC, rolljee approved these changes

2021-04-12 15:50 UTC, alexandrebouthinon requested changes
This is a CI/CD update. Do not perform a version bump 🙁

2021-04-12 21:18 UTC, Aschen commented
:+1: with @alexandrebouthinon 

Also the tag should be `changelog:exclude` since this PR won't affect the code

2021-04-13 11:21 UTC, Aschen approved these changes

2021-04-14 12:28 UTC, Leodau approved these changes

2021-04-14 15:24 UTC, merged