Add bulk:updateByQuery and document:mUpsert
kuzzleio/sdk-javascript pull request #633
Opened 2021-04-23 09:03 UTC by Yoann-Abbes

## What does this PR do ?

Add `bulk:updateByQuery` and `document:mUpsert` api actions

2021-04-30 12:04 UTC, scottinet requested changes

2021-04-30 12:04 UTC, scottinet commented on doc/7/controllers/document/m-upsert/index.md
> +| `documents`  | <pre>object[]</pre> | Array of documents to update |
Kuzzle expects a particular format for this argument (same as for single upserts). This should be detailed, especially considering that the sample code is missing the case where documents get created with default values.

2021-04-30 12:04 UTC, scottinet commented on doc/7/controllers/document/m-upsert/snippets/m-upsert.js
> +  ];
(nitpicking) It would be nice to create a new document on the fly, with default value(s)

2021-05-03 08:16 UTC, rolljee approved these changes

2021-05-03 09:06 UTC, Shiranuit approved these changes
Just appy the requested changes and this will be good for me 👍

2021-05-05 07:50 UTC, scottinet approved these changes

2021-05-05 07:50 UTC, scottinet commented on doc/7/controllers/document/m-upsert/index.md
> +`documents` is an array of object which each object represents a document. Fields `_id` and `changes` is always mandatory while `default` is optional.
```suggestion
`documents` is an array of object which each object representing a document. Fields `_id` and `changes` is always mandatory while `default` is optional.
```

2021-05-05 07:50 UTC, scottinet commented on doc/7/controllers/document/m-upsert/snippets/m-upsert.js
> +  await kuzzle.document.create('nyc-open-data', 'yellow-taxi', doc2, 'some-other-id');
(nitpicking) I would remove that line to make your code update a document, and create another one, all in one go.

```suggestion
```

2021-05-13 18:02 UTC, Aschen requested changes
Also you should add the `timeout` option from @Shiranuit  PR

2021-05-13 18:02 UTC, Aschen commented on doc/7/controllers/bulk/update-by-query/index.md
> +| `searchQuery` | <pre>object</pre> | Query to match                            |
Should match the method parameter name `query`

2021-05-27 09:42 UTC, Aschen approved these changes

2021-05-31 09:51 UTC, merged