Feature document:deleteFields
kuzzleio/sdk-javascript pull request #636
Opened 2021-05-11 12:58 UTC by Shiranuit

## What does this PR do ?
This PR add the action `document:deleteFields` and the associated documentation and tests

2021-05-13 18:04 UTC, Aschen requested changes
You should add the `timeout` option from your other PR

2021-05-13 18:04 UTC, Aschen commented on src/controllers/Document.ts
> +    fields: Array<string>,
Prefer the more concise `string[]`

2021-05-16 21:17 UTC, MathieuVeber approved these changes
LGTM :wink:

2021-05-25 08:43 UTC, Aschen approved these changes

2021-05-27 10:55 UTC, Leodau approved these changes

2021-05-27 10:55 UTC, Leodau commented on doc/7/controllers/document/delete-fields/snippets/deleteFields.js
> +  const response = await kuzzle.document.deleteFields('nyc-open-data', 'yellow-taxi', 'some-id', ['bar'], {source: true});
Nit
```suggestion
  const response = await kuzzle.document.deleteFields('nyc-open-data', 'yellow-taxi', 'some-id', ['bar'], { source: true });
```

2021-05-27 11:34 UTC, merged