Add an origin parameter to the kuzzle disconnected event
kuzzleio/sdk-javascript pull request #639
Opened 2021-05-26 14:16 UTC by Shiranuit

## What does this PR do ?
This PR adds an `origin` parameter to the Kuzzle disconnected event.
This parameter describes what is causing the disconnected event.

**Origins**

| Name                     | Description                                                                                                                                                        |
| ------------------------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| `websocket/auth-renewal` | The websocket protocol si reconnecting to renew the token. See [Websocket Cookie Authentication](sdk/js/7/protocols/websocket/introduction#cookie-authentication). |
| `user/connection-closed` | The disconnection is done by the user.                                                                                                                             |
| `network/error`          | An network error occured and caused a disconnection.                                                                                                               |
### How should this be manually tested?

```bash
npm run test
```

2021-05-26 14:41 UTC, Yoann-Abbes commented on doc/7/essentials/events/index.md
> +**Callback arguments:**
Missing SinceBadge Version

2021-05-26 14:55 UTC, Yoann-Abbes approved these changes

2021-05-26 14:55 UTC, jenow commented on src/Kuzzle.ts
> +    this.protocol.addListener('disconnect', (context) => {
```suggestion
    this.protocol.addListener('disconnect', context => {
```

2021-05-26 15:47 UTC, jenow approved these changes

2021-05-27 06:35 UTC, Aschen requested changes

2021-05-27 06:35 UTC, Aschen commented on doc/7/essentials/events/index.md
> +| `network/connection-closed` | The disconnection is either manual or issued by Kuzzle                                                                                                             |
We could have `user/connection-closed` instead since the action is not initiated by the network layer but by the user

2021-05-27 09:35 UTC, Aschen approved these changes

2021-05-27 11:34 UTC, merged