Add support and documentation to use API keys
kuzzleio/sdk-javascript pull request #724
Opened 2023-02-23 14:26 UTC by ScreamZ

2023-02-24 19:49 UTC, Aschen requested changes

2023-02-25 10:57 UTC, ScreamZ commented on src/Kuzzle.ts
> +    if (apiKey.match(/^kapikey-/) === null)
J'y ai pensé, mais je me suis fais avoir quelque fois du fait que c'est du ES6, surtout sur React Native
-> https://stackoverflow.com/questions/70584592/getting-startswith-is-not-a-function-in-react-native

Normalement le support est mieux maintenant avec : https://reactnative.dev/docs/javascript-environment#ecmascript-2015-es6 mais qui peut le plus peut le moins donc je me suis dis que la bonne vieille regexp ça marche aussi. :)

What do you think ?

2023-02-25 10:59 UTC, ScreamZ commented on src/Kuzzle.ts
> +      throw new Error("This is not a valid API key");
Est-ce qu'on mettrait pas plutôt 
> Invalid API key. Did you generated it using `kuzzle.auth.createApiKey`? J'aime pas trop leaker les détails d'implémentation sur le prefix, après on a peut-être des trolls qui vont essayer de rajouter `kapikey-` sur leur clé qui marche pas juste pour tester xD

Est-ce qu'on rendrais pas la fonction asynchrone pour aller vérifier la clé ?

2023-02-27 15:07 UTC, Aschen commented on src/Kuzzle.ts
> +    if (apiKey.match(/^kapikey-/) === null)
Oh I didn't know that it was missing in React Native! (The CI would have catch this)

You can leave the regexp then

2023-02-27 15:09 UTC, Aschen commented on src/Kuzzle.ts
> +      throw new Error("This is not a valid API key");
I don't think it's necessary to check the key validity here, anyway an error will be returned with the first query (we try to keep the SDK as simple as possible)

The prefix it's here precisely for developers to read it so they can figure out what they are manipulating. Also it helps to detect stolen or forgotten API key (e.g. [in Github repositories](https://docs.github.com/en/code-security/secret-scanning/secret-scanning-partner-program))

2023-02-27 19:49 UTC, ScreamZ commented on src/Kuzzle.ts
> +      throw new Error("This is not a valid API key");
@Aschen Fixed, ready

2023-02-28 10:01 UTC, Shiranuit approved these changes

2023-02-28 10:17 UTC, alexandrebouthinon approved these changes

2023-02-28 14:25 UTC, alexandrebouthinon requested changes

2023-02-28 14:25 UTC, alexandrebouthinon commented on src/Kuzzle.ts
> +  }
To make your code pass our linting rules 🙂 
```suggestion
  public setAPIKey(apiKey: string) {
    if (apiKey.match(/^kapikey-/) === null) {
      throw new Error("Invalid API key. Missing the `kapikey-` prefix.");
    }

    this.jwt = apiKey;
  }
```

2023-02-28 21:03 UTC, ScreamZ commented
@alexandrebouthinon Why eslint is not part of devDevs ? That why i didn't triggered in my IDE :) btw all fixed

2023-03-01 15:45 UTC, ScreamZ commented
Look like the CI for snippets is broken
https://github.com/kuzzleio/sdk-javascript/actions/runs/4297391545/jobs/7506793064

Also cannot test locally https://discord.com/channels/306054601436561410/1080514356460126268

2023-03-02 18:16 UTC, merged